###
#   Default config for anisotropy
#
#   Special values:
#       theta = [min, max, step]
#       thickness = [min, max]
##

[logger]
name = "anisotropy"
format = "%(levelname)s: %(message)s"

[base]
simple = true 
bodyCentered = false 
faceCentered = true

###
#   Simple
##
[simple.parameters]
theta = [0.01, 0.28, 0.01]

[simple.geometry]
directions = [
    [1, 0, 0],
    [0, 0, 1],
    [1, 1, 1]
]
fillet = true

[simple.mesh]
fineness = 3
minSize = 0.05
maxSize = 0.1
growthRate = 0.5
nbSegPerEdge = 0.5
nbSegPerRadius = 0.5
chordalErrorEnabled = false
chordalError = -1
secondOrder = false
optimize = true
quadAllowed = false
useSurfaceCurvature = true
fuseEdges = true
checkChartBoundary = false

localSizeOnShape.strips = 0.01

viscousLayers = true
thickness = [0.01, 0.005]
numberOfLayers = 1
stretchFactor = 1.2
isFacesToIgnore = true

###
#   Body-centered
##
[bodyCentered.parameters]
# TODO: 0.18 
theta = [0.01, 0.17, 0.01]

[bodyCentered.geometry]
directions = [
    [1, 0, 0],
    [0, 0, 1],
    [1, 1, 1]
]
fillet = true

[bodyCentered.mesh]
fineness = 3
minSize = 0.05
maxSize = 0.5
growthRate = 0.5
nbSegPerEdge = 0.5
nbSegPerRadius = 0.5
chordalErrorEnabled = false
chordalError = -1
secondOrder = false
optimize = true
quadAllowed = false
useSurfaceCurvature = true
fuseEdges = true
checkChartBoundary = false

localSizeOnShape.strips = 0.01

viscousLayers = true
thickness = [0.005, 0.0005]
numberOfLayers = 1
stretchFactor = 1.2
isFacesToIgnore = true

###
#   Face-centered
##
[faceCentered.parameters]
theta = [0.01, 0.13, 0.01]

[faceCentered.geometry]
directions = [
    [1, 0, 0],
    [0, 0, 1],
    [1, 1, 1]
]
fillet = true

[faceCentered.mesh]
fineness = 3
minSize = 0.01
maxSize = 0.5
growthRate = 0.5
nbSegPerEdge = 0.5
nbSegPerRadius = 0.5
chordalErrorEnabled = false
chordalError = -1
secondOrder = false
optimize = true
quadAllowed = false
useSurfaceCurvature = true
fuseEdges = true
checkChartBoundary = false

localSizeOnShape.strips = 0.01

viscousLayers = true
thickness = [0.001, 0.0005]
numberOfLayers = 1
stretchFactor = 1.2
isFacesToIgnore = true

###
#   Flow
##
[flow]
scale = [1e-5, 1e-5, 1e-5]

[flow.constant]
nu = 1e-6

[flow.approx.pressure.boundaryField]
inlet.type = "fixedValue"
inlet.value = 1e-3
outlet.type = "fixedValue"
outlet.value = 0

[flow.approx.velocity.boundaryField]
inlet.type = "fixedValue"
inlet.value = [
    [ 6e-5, 6e-5,   0.0 ],
    [ 0.0,  0.0,    6e-5 ],
    [ 6e-5, 6e-5,   6e-5 ]
]
outlet.type = "zeroGradient"
outlet.value = "None"

[flow.main.pressure.boundaryField]
inlet.type = "fixedValue"
inlet.value = 1e-3
outlet.type = "fixedValue"
outlet.value = 0

[flow.main.velocity.boundaryField]
inlet.type = "pressureInletVelocity"
inlet.value = [
    [ 0, 0, 0 ],
    [ 0, 0, 0 ],
    [ 0, 0, 0 ]
]
outlet.type = "zeroGradient"
outlet.value = "None"


