[logger]
name = "anisotropy"
format = "%(levelname)s: %(message)s"

[base]
simple = true
bodyCentered = true
faceCentered = true

[simple]
theta = [0.01, 0.28]

[simple.geometry]
directions = [
    [1, 0, 0],
    [0, 0, 1],
    [1, 1, 1]
]
fillet = true

[simple.mesh]
fineness = 3
minSize = 0.01
maxSize = 0.1
growthRate = 0.5
nbSegPerEdge = 0.5
nbSegPerRadius = 0.5
chordalErrorEnabled = false
chordalError = -1
secondOrder = false
optimize = true
quadAllowed = false
useSurfaceCurvature = true
fuseEdges = true
checkChartBoundary = false

thickness = 0.005
numberOfLayers = 2
stretchFactor = 1.2
isFacesToIgnore = true

[bodyCentered]
theta = [0.01, 0.18]

[bodyCentered.geometry]
directions = [
    [1, 0, 0],
    [0, 0, 1],
    [1, 1, 1]
]
fillet = true

[bodyCentered.mesh]
fineness = 3
minSize = 0.005
maxSize = 0.05
growthRate = 0.5
nbSegPerEdge = 0.5
nbSegPerRadius = 0.5
chordalErrorEnabled = false
chordalError = -1
secondOrder = false
optimize = true
quadAllowed = false
useSurfaceCurvature = true
fuseEdges = true
checkChartBoundary = false

thickness = 0.005
numberOfLayers = 2
stretchFactor = 1.2
isFacesToIgnore = true

[faceCentered]
theta = [0.01, 0.13]

[faceCentered.geometry]
directions = [
    [1, 0, 0],
    [0, 0, 1],
    [1, 1, 1]
]
fillet = true

[faceCentered.mesh]
fineness = 3
minSize = 0.005
maxSize = 0.05
growthRate = 0.5
nbSegPerEdge = 0.5
nbSegPerRadius = 0.5
chordalErrorEnabled = false
chordalError = -1
secondOrder = false
optimize = true
quadAllowed = false
useSurfaceCurvature = true
fuseEdges = true
checkChartBoundary = false

thickness = 0.001
numberOfLayers = 2
stretchFactor = 1.2
isFacesToIgnore = true

