###
#   Default config for anisotropy
#
#   Special values:
#       theta = [min, max, step]
#       thickness = [min, max]
##

[logger]
name = "anisotropy"
format = "%(levelname)s: %(message)s"

[base]
simple = false 
bodyCentered = false 
faceCentered = true 

[[structures]]
    name = "simple"

    [structures.geometry]
    theta = [0.01, 0.28, 0.01]
    directions = [
        [1, 0, 0],
        [0, 0, 1],
        [1, 1, 1]
    ]
    fillet = true

    [structures.mesh]
    viscousLayers = true 
    thickness = [0.01, 0.005]

    [structures.submesh.strips]
    growthRate = 0.2
    nbSegPerEdge = 2
    nbSegPerRadius = 3

[[structures]]
    name = "bodyCentered"

    [structures.geometry]
    theta = [0.01, 0.17, 0.01]
    directions = [
        [1, 0, 0],
        [0, 0, 1],
        [1, 1, 1]
    ]
    fillet = true

    [structures.mesh]
    viscousLayers = true 
    thickness = [0.005, 0.0005]

    [structures.submesh.strips]
    growthRate = 0.2
    nbSegPerEdge = 2
    nbSegPerRadius = 3

[[structures]]
    name = "faceCentered"

    [structures.geometry]
    theta = [0.01, 0.13, 0.01]
    directions = [
        [1, 0, 0],
        [0, 0, 1],
        [1, 1, 1]
    ]
    fillet = true

    [structures.mesh]
    viscousLayers = true 
    thickness = [0.001, 0.0005]

    [structures.submesh.strips]
    growthRate = 0.2
    nbSegPerEdge = 2
    nbSegPerRadius = 3

