# -*- coding: utf-8 -*-
# This file is part of anisotropy.
# License: GNU GPL version 3, see the file "LICENSE" for details.

[logger]
name = "anisotropy"
format = "[ %(levelname)s ] %(message)s"

[base]
simple = true 
bodyCentered = true 
faceCentered = true 

[[structures]]
    type = "simple"
    theta = [0.01, 0.28]
    thetaStep = 0.01
    directions = [  
        [1, 0, 0],
        [0, 0, 1],
        [1, 1, 1]
    ]
    r0 = 1 
    filletsEnabled = true

[[structures]]
    type = "bodyCentered"
    theta = [0.01, 0.17]
    thetaStep = 0.01
    directions = [  
        [1, 0, 0],
        [0, 0, 1],
        [1, 1, 1]
    ]
    r0 = 1 
    filletsEnabled = true

[[structures]]
    type = "faceCentered"
    theta = [0.01, 0.12]
    thetaStep = 0.01
    directions = [  
        [1, 0, 0],
        [0, 0, 1],
        [1, 1, 1]
    ]
    r0 = 1 
    filletsEnabled = true


